[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# add surreal db as dependancy
tokio = { version = "1", features = ["full"] }
anyhow = "1"
surrealdb = "1.0.0-beta.8"
